stages:
    00-pci-seurat-import:
        cmd: Rscript pci_seurat_import.R
        wdir: code/
        deps:
            - ../analysis/seurat/20200816/pci_filtered_seurat_object.rdat
            - pci_seurat_import.R
        outs:
            - ../analysis/pci_import/
    01-liger-seurat-import:
        cmd: Rscript liger_seurat_import.R
        wdir: code/
        deps:
            - ../analysis/liger_subcluster/20200824
            - liger_seurat_import.R
        outs:
            - ../analysis/seurat_lchen/liger_subcluster_metadata.rds
            - ../analysis/seurat_lchen/liger_subcluster_metadata.csv
    02-seurat-excitatory-layers:
        cmd: Rscript seurat_excitatory_layers.R
        wdir: code/
        deps:
            - seurat_excitatory_layers.R
            - ../resources/excitatory_layers_20210318.csv
            - ../analysis/pci_import/pci_seurat.rds
        outs:
            - ../analysis/seurat_lchen/seurat_excitatory_layers/ct_layer.csv
            - ../analysis/seurat_lchen/seurat_excitatory_layers/excitatory_markers.pdf
            - ../analysis/seurat_lchen/seurat_excitatory_layers/sobj_celltype_meta.rds
    03-seurat-cluster-lme:
        cmd: Rscript seurat_cluster_lme.R
        wdir: code/seurat_cluster_dge
        deps:
            - seurat_cluster_lme.R
            - "../../analysis/pci_import/pci_seurat.rds"
            - "../../analysis/seurat_lchen/seurat_excitatory_layers/sobj_celltype_meta.rds"
        outs:
            - "../../analysis/seurat_lchen/seurat_cluster_lme/cluster_wk.rds"
            - "../../analysis/seurat_lchen/seurat_cluster_lme/lme_tables"
    04-seurat-celltype-dge-overlap:
        cmd: Rscript seurat_celltype_dge_overlap.R
        wdir: code/seurat_cluster_plots
        deps:
            - seurat_celltype_dge_overlap.R
            - "../../analysis/seurat_lchen/seurat_cluster_lme/cluster_wk.rds"
        outs:
            - ../../analysis/seurat_lchen/seurat_cluster_lme/celltype_dge_overlaps.pdf
    seurat-umap:
        cmd: Rscript seruat_umap.R
        wdir: code/
        deps:
            - seurat_umap.R
            - "../analysis/pci_import/pci_seurat.rds"
            - "../analysis/seurat_lchen/seurat_excitatory_layers/sobj_celltype_meta.rds"
            - "../resources/Immune_markers_toplot_2021.xlsx"
        outs:
            - "../analysis/seurat_lchen/seurat_umap/"


