stages:
    00-pci-seurat-import:
        cmd: Rscript pci_seurat_import.R
        wdir: code/
        deps:
            - ../analysis/seurat/20200816/pci_filtered_seurat_object.rdat
            - pci_seurat_import.R
        outs:
            - ../analysis/pci_import/
    01-liger-seurat-import:
        cmd: Rscript liger_seurat_import.R
        wdir: code/
        deps:
            - ../analysis/liger_subcluster/20200824
            - liger_seurat_import.R
        outs:
            - ../analysis/seurat_lchen/liger_subcluster_metadata.rds
            - ../analysis/seurat_lchen/liger_subcluster_meta.csv
    02-seurat-excitatory-layers:
        cmd: Rscript seurat_excitatory_layers.R
        wdir: code/
        deps:
            - seurat_excitatory_layers.R
            - ../resources/excitatory_layers_20210318.csv
            - ../analysis/pci_import/pci_seurat.rds
        outs:
            - ../analysis/seurat_lchen/seurat_excitatory_layers/ct_layer.csv
            - ../analysis/seurat_lchen/seurat_excitatory_layers/excitatory_markers.pdf
            - ../analysis/seurat_lchen/seurat_excitatory_layers/sobj_celltype_meta.rds

