channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1.3
  - python=3.10
  - r-rcpp
  - r-singlecellexperiment
  - r-lmertest
  - r-liger=0.5.0.9000
  - r-batchtools
  - bioconductor-impute
  - r-broom.mixed
  - r-eulerr
  - bioconductor-edger
  - r-tidyverse=1.3.1
  - r-ggcorrplot
  - r-cowplot
  - r-ggally
  - r-matrix
  - bioconductor-complexheatmap
  - r-ggrastr
  - r-ggpubr
  - r-wgcna
  - bioconductor-variancepartition
  - r-viridis
  - r-multcomp
  - r-seurat=4.1.0
  - r-ggfortify
  - r-spatstat
  - r-ggalt
  - r-svglite
  - r-argparse
  - bioconductor-aucell
  - bioconductor-rcistarget
  - bioconductor-genie3
  - arboreto
  - r-dt
  - r-nmf
  - r-r2html
  - r-rtsne
  - r-domc
  - r-dorng
